title: A test Github blog site using Jekill
author: padames
email: pablo.adames@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  A test Github blog site using Jekill

theme: minima

# social links
twitter_username: PAdames1 # DO NOT include the @ character, or else the build will fail!
github_username:  padames # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
